name: Test

on: 
  [push]

jobs:
  Newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install newman
      - run: npm install -g newman
      - name: Running postman collection
      - run: npm run test-api