name: test

on: 
  [push]

jobs:
  Test:
    runs_on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run test