name: Test

on: 
  [push]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install modules
      - run: yarn
      - run: npm install
      - run: npm ci
      - run: npm run test-smoke

  Newman:
    runs-on: ubuntu-latest
    needs: Lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install newman
      - run: npm install -g newman
      - name: Running postman collection
      - run: npm run test-api

  Smoke:
    runs-on: ubuntu-latest
    needs: Newman
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm ci
      - run: npm run test-smoke
